### ISSUE TITLE
Permettre des paramètres dans l'entête

### ISSUE THREAD

**Issue by LotuxPunk** [gaetanledocte/gaetanledocte.github.io#3]
Hello ! Ce serait cool d'avoir des paramètres dans l'entête des modules.
Un truc comme ça : 
`---*module(MonModule;x, y;resultat)`
Mes compétences en JS par contre sont, pour le moment, insuffisantes pour te faire quelque chose en code. 😞

**Comment by gaetanledocte** [comment]
Je ne comprend pas vraiment le principe. En soi, tu peux déjà le faire actuellement. Pourrais-tu détailler ta suggestion (avec un schéma plus visuel ?). Merci !

**Comment by LotuxPunk** [comment]
Un truc dans ce genre là. Ce qui permettrait d'avoir les variables du module en entête et de ne pas devoir utiliser forcément celle donnée en argument.
![schema da](https://user-images.githubusercontent.com/16562647/32846864-ae244ee4-ca28-11e7-94bf-831f9f8cff26.png)

**Comment by gaetanledocte** [comment]
L'idée proposée sur le schéma me semble complexifier la lecture finale du diagramme.
Néanmoins, j'ai réfléchi à l'idée proposée à la base : "mettre des paramètres dans l'entête des modules".
Et après avoir cherché une notation simple, je suis arrivé à ceci :

```
┌─── * Principal
│ terme1 = 10
│ terme2 = 15
│ o─────────────o ↓ terme1, terme2
│ │ SommeTermes │
│ o─────────────o ↓ somme
│ Sortir somme
└──────────
 
┌─── * SommeTermes : (terme1, terme2) → (somme)
│ somme = terme1 + terme2
└──────────
```
Plus particulièrement, ceci :
```
┌─── * SommeTermes : (terme1, terme2) → (somme)
```
Ceci est une notation permettant de spécifier les paramètres et les retours d'un module.
La lecture reste simple et clair.

A noter que cette écriture est faisable avec la version actuelle du parser.

**Comment by LotuxPunk** [comment]
C'est pas faux ! 👍
