### ISSUE TITLE
Bug à l'impression si trop long

### ISSUE THREAD

**Issue by LotuxPunk** [gaetanledocte/gaetanledocte.github.io#7]
Yop ! Petit truc remarqué à l'examen lors de l'impression : 
Exemple de DA : 
```
---*
phrase = Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et olore magna aliqua.
------
```
Résultat : 
![image](https://user-images.githubusercontent.com/16562647/34906796-98b5a4f2-f874-11e7-8667-2d4c13eb7353.png)

**Comment by gaetanledocte** [comment]
Oui, c'est effectivement un problème connu.

Il est possible de faire "casser" la fin de la ligne automatiquement pour avoir un retour à la ligne correct. Le problème est que, dans ce cas, on perd les "bordures" à gauche ("│", "║")...
Pour garder ces bordures, il faudrait gérer les différents format d'impression (A4, A5, marges différentes, ...) pour savoir quand casser la ligne et ajouter ces bordures au début de la nouvelle ligne -> complexe.

Comme ce cas de figure ne se produit pas régulièrement, je préfère privilégier la solution suivante :
-  ne pas effectuer de retour à la ligne systématique
- laisser l'utilisateur faire des retours à la ligne manuel dans la source ; ce qui a pour effet de formater correctement le texte
- l'utilisateur peut se servir de "l'aperçu avant impression" de son navigateur pour savoir quand effectuer un retour à la ligne
